### ISSUE TITLE
Design issue with long repo names

### ISSUE THREAD

**Issue by arthurvr** [h5bp/h5bp.github.io#19]
When one (or more) of the 'latest updated' repos has a long name, like `Front-end-Developer-Interview-Questions` or `html5boilerplate.com-mobile`, the design kinda breaks:

![screenshot 2014-12-23 08 52 03](https://cloud.githubusercontent.com/assets/6025224/5535532/05cbf9f2-8a81-11e4-8582-43ec5a630f86.png)

Does somebody have any ideas how to fix this nicely?

**Comment by arthurvr** [comment]
I still do wonder how we can fix this nicely while keeping this design :/

**Comment by roblarsen** [comment]
should be closed with #30
