### ISSUE TITLE
Use 'main.css' for this site

### ISSUE THREAD

**Issue by coliff** [h5bp/h5bp.github.io#38]
it'd be nice to use our own 'main.css' for this site - imported via NPM - like we do for H5BP. Right now, we do include the CSS but it's out of sync so importing via NPM would keep it up to date.

**Comment by roblarsen** [comment]
@coliff any thoughts on how to do this cleanly? This is just a static site, so there's not really a build step we can rely on.

**Comment by coliff** [comment]
oh right... good point. We could load it minified from the JSDelivr CDN.
https://cdn.jsdelivr.net/npm/main.css@1.0.0/dist/main.min.css

This is an undocumented way of using 'main.css' though... maybe we could add this as an alternative way of using it to main.css to that projects README.

**Comment by coliff** [comment]
Live! https://h5bp.org/
